[project]
name = "kvrocks_dao"
version = "0.0.6"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "Testing"
readme = "readme.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]