
[tool.black]
line-length = 100
verbose = true

[tool.poetry]
name = "elasticcsv"
version = "0.3.0"
description = "elasticsearch csv upload download utility"
authors = ["J. Andres Guerrero <juguerre@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.scripts]
csv2es = "elasticcsv.csv2es:app"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
pandas = "^2"
elasticsearch = {version = "^8", extras = ["async"]}
pyyaml = "^6"
python-box = "^7"
tqdm = "^4"
requests = "^2"
pytz = "^2024"
typer = {extras = ["all"], version = "^0.9.0"}
toolz = "^0"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3"
pytest = "^7"
pytest-mock = "^3"
testcontainers = "^3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
