[tool.poetry]
name = "zyxel-nebula-client"
version = "0.1.3"
description = "Python Client for interacting with the Zyxel Nebula API"
authors = ["Cem Basoglu <cem.basoglu@web.de>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/cemizm/zyxel-nebula-client"

[tool.poetry.dependencies]
python = "^3.12"
httpx = "^0.27.2"
dacite = "^1.8.1"

[tool.poetry.group.dev.dependencies]
pytest-httpx = "^0.33.0"
pytest = "^8.3.3"
pytest-asyncio = "^0.24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api" 