# https://peps.python.org/pep-0621/#example
# https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata

[project]
name = 'bcmd'
version = '0.4.8'
description = 'Commands for Beni'
requires-python = '>=3.10'
keywords = ['benimang', 'beni', 'bcmd']
authors = [{ name = 'Beni Mang', email = 'benimang@126.com' }]
maintainers = [{ name = 'Beni Mang', email = 'benimang@126.com' }]


dependencies = [
  'benimang==0.6.8',
  'build',
  'cryptography',
  'pathspec',
  'pillow',
  'prettytable',
  'psutil',
  'qiniu==7.13.2',
  'twine',
  'typer',
  # 'setuptools',
]

[project.scripts]
beni = 'bcmd.main:run'
