[tool.poetry]
name = "latexcor"
version = "0.3.4"
description = ""
authors = ["infocornouaille <90894019+infocornouaille@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
chardet = "^5.2.0"
typer = "^0.12.5"
python-slugify = "^7.0.0"
PyYAML = "^6.0.2"
tomli = "^2.0.2"
watchdog = "^5.0.3"
rich = "^13.9.3"
pydantic = "^2.9.2"
dockercor = "^0.1.2"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
pytest = "^8.3.3"
isort = "^5.13.2"

[tool.poetry.scripts]
latexcor= 'latexcor.cli:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
