[package]
name = "path_toolkit"
version = "0.2.0"
edition = "2021"

[lib]
name = "path_toolkit"
crate-type = ["cdylib", "lib"]

[dependencies]
pyo3 = { version = "0.22.5", features = ["extension-module"] }
numpy = "0.22.1"

ndarray = "0.15.6"
ndarray-linalg = { version = "0.16.0", features = ["openblas-system"] }
splines = "4.4.0"
simple_qp = "0.2.2"
