[tool.poetry]
name = "datamarket"
version = "0.7.1"
description = "Utilities that integrate advanced scraping knowledge into just one library."
authors = ["DataMarket <techsupport@datamarket.es>"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://datamarket.es"
repository = "https://github.com/Data-Market/datamarket"
documentation = "https://github.com/Data-Market/datamarket"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.9"
typer = "0.12.5"
SQLAlchemy = "2.0.36"
psycopg2-binary = "2.9.10"
requests = "2.32.3"
tenacity = "9.0.0"
beautifulsoup4 = "4.12.3"
pre-commit = "4.0.1"

boto3 = {version = "1.35.53", optional = true}
unidecode = {version = "1.3.8", optional = true}
lxml = {version = "5.3.0", optional = true}
tqdm = {version = "4.66.6", optional = true}
pendulum = {version = "3.0.0", optional = true}
pandas = {version = "2.2.3", optional = true}
pyarrow = {version = "17.0.0", optional = true}
pytest = {version = "8.3.3", optional = true}
playwright = {version = "1.47.0", optional = true}
soda-core-postgres = {version = "3.4.1", optional = true}
fake-useragent = {version = "1.5.1", optional = true}
croniter = {version = "3.0.4", optional = true}
pydrive2 = {version = "1.20.0", optional = true}
clickhouse-driver = {version = "0.2.9", optional = true}
stem = {version = "1.8.2", optional = true}
click = {version = "8.1.7", optional = true}
rapidfuzz = {version = "3.10.1", optional = true}
demjson3 = {version = "3.0.6", optional = true}
geopy = {version = "2.4.1", optional = true}
nodriver = {version = "0.37", optional = true}
undetected-chromedriver = {version = "3.5.5", optional = true}
retry = {version = "0.9.2", optional = true}
shapely = {version = "2.0.6", optional = true}
geopandas = {version = "1.0.1", optional = true}
chompjs = {version = "1.3.0", optional = true}
pillow = {version = "11.0.0", optional = true}
duckduckgo-search = {version = "6.3.3", optional = true}
pysocks = {version = "1.7.1", optional = true}

[tool.poetry.extras]
boto3 = ["boto3"]
unidecode = ["unidecode"]
lxml = ["lxml"]
tqdm = ["tqdm"]
pendulum = ["pendulum"]
pandas = ["pandas"]
pyarrow = ["pyarrow"]
pytest = ["pytest"]
playwright = ["playwright"]
soda-core-postgres = ["soda-core-postgres"]
fake-useragent = ["fake-useragent"]
croniter = ["croniter"]
pydrive2 = ["pydrive2"]
clickhouse-driver = ["clickhouse-driver"]
stem = ["stem"]
click = ["click"]
rapidfuzz = ["rapidfuzz"]
demjson3 = ["demjson3"]
geopy = ["geopy"]
nodriver = ["nodriver"]
retry = ["retry"]
shapely = ["shapely"]
geopandas = ["geopandas"]
chompjs = ["chompjs"]
pillow = ["pillow"]
duckduckgo-search = ["duckduckgo-search"]
pysocks = ["pysocks"]

# Interface groups
aws = ["boto3"]
drive = ["pydrive2"]
peerdb = ["boto3", "clickhouse-driver"]
proxy = ["stem"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
