[build-system]
requires=[
    "setuptools>=42",
    "wheel",
    "build"
]
build-backend="setuptools.build_meta"

[tool.mypy]

[project]
name="civitai-model-downloader"
version="0.3.17"

requires-python=">=3.8, <3.13"
authors=[
    {name="Hyunbeen Chang", email="bean980310@gmail.com"}
]
maintainers=[
    {name="Hyunbeen Chang", email="bean980310@gmail.com"}
]
description="A package to download models from CivitAI"
readme="README.md"
license={file="LICENSE"}
keywords=["civitai"]
classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
]
dynamic=["dependencies"]

[tool.setuptools.dynamic]
dependencies={file=["requirements.txt"]}

[project.urls]
Repository = "https://github.com/bean980310/civitai-downloader"
"Bug Tracker" = "https://github.com/bean980310/civitai-downloader/issues"
Changelog = "https://github.com/bean980310/civitai-downloader/blob/master/CHANGELOG.md"

[project.scripts]
civitai-downloader-cli="civitai_downloader.__main__:main"