[build-system]
requires = ["setuptools>=45", "wheel"]  # Specify the minimum requirements for building the project
build-backend = "setuptools.build_meta"  # Use setuptools as the build backend

[project]  # Project metadata
name = "crud-forge"
version = "0.3.1"
description = "A package for generating FastAPI CRUD operations and routes"
requires-python = ">=3.10"
license = { text = "MIT" }
readme = "README.md"
authors = [{name = "Yrrrrrf", email = "fernandorezacampos@gmail.com"}]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "fastapi>=0.111.0",
    "sqlalchemy>=2.0.30",
    "pydantic>=2.7.1",
    "psycopg2>=2.9.3",
    # asyncpg
    # psycopg2-binary
]

# Optional dependencies for development
[project.optional-dependencies]
dev = [
    "pytest>=6.2.5,<7.0.0",
    "black>=21.9b0,<22.0.0",
    "isort>=5.9.3,<6.0.0",
    "mypy>=0.910,<1.0",
]

[project.urls]
Homepage = "https://github.com/Yrrrrrf/crud-forge"
Repository = "https://github.com/Yrrrrrf/crud-forge"

[tool.setuptools]  # Configure setuptools to look for packages in the src directory
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]  # Find packages in the src directory

[tool.black]  # Configure Black code formatter
line-length = 88  # Maximum line length
target-version = ['py310', 'py311', 'py312']  # Target Python versions
include = '\.pyi?$'  # Include .pyi files
extend-exclude = '''
/(
  # Exclude these directories from formatting
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]  # Configure isort import sorter
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
