[tool.poetry]
name = "macrosaurus"
version = "0.0.3"
description = "Versatile LLMs that works out of the box."
authors = ["amoooooo <amor.budiyanto2006@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
openai = "^1.52.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
