[project]
name = "mkBot"
dependencies = ["pyTelegramBotAPI"]
version = "1.0.0"

authors = [
  { name="moh0009", email="23ii.mancy@gmail.com" },
]

description = "An easy way to crate inline Telegram bots and you can get json file from the user answers"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
Homepage = "https://github.com/moh0009/mkBot"
Issues = "https://github.com/moh0009/mkBot/issues"