[tool.poetry]
name = "briton"
version = "0.3.7-dev.2"
description = "Python component of using Briton"
authors = ["Pankaj Gupta <pankaj@baseten.co>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
grpcio = "^1.62.3"
grpcio-tools = "^1.62.3"
transformers = "4.46.0"
pydantic = "^2.9.2"
outlines = "0.0.46"
torch = "^2.4.1"
fastapi = "^0.114.0"
huggingface-hub = "^0.25.2"
hf-transfer = "^0.1.8"
openai = "^1.51.2"
sentencepiece = "^0.2.0"
psutil = "5.9.4"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
ipdb = "^0.13.13"
ipython = "^8.28.0"
pytest-asyncio = "^0.24.0"
black = "^24.10.0"
isort = "^5.13.2"
twine = "^5.1.1"
mypy-protobuf = "^3.6.0"
