[tool.poetry]
name = "moy-nalog"
version = "0.1.5"
description = "Async Python API for lknpd.nalog.ru"
authors = ["Ben Puls <mail@benpuls.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
httpx = "^0.27.2"


[tool.poetry.group.dev.dependencies]
ruff = "^0.7.1"
pytest = "^8.3.3"
pytest-asyncio = "^0.24.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
