[tool.poetry]
name = "ntinput"
version = "1.1.0"
description = "Simple library to manipulate mouse and keyboard using shadowed syscall functions"
authors = ["Xenely <amaryatkin@vk.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
