[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cheutils"
version = "2.5.1"
authors = [
  { name="Ferdinand Che", email="ferdinand.che@gmail.com" },
]
description = "A set of basic reusable utilities and tools to facilitate quickly getting up and going on any machine learning project."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/chewitty/cheutils"
Issues = "https://github.com/chewitty/cheutils/issues"