[project]
name = "django-stagers"
version = "0.0.1"
authors = [
  { name="Matthew Coleman", email="19colemanm@gmail.com" },
]
description = "This package adds stagers to assist in bulk operations on django models."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = [
    "setuptools>=61.0",
    "django>=4.0.0"
]
build-backend = "setuptools.build_meta"
