[package]
name = "rattler_solve"
version = "1.2.0"
edition= "2021"
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "A crate to solve conda environments"
categories= ["development-tools"]
homepage= "https://github.com/conda/rattler"
repository= "https://github.com/conda/rattler"
license= "BSD-3-Clause"
readme= "README.md"
resolver = "2"

[dependencies]
rattler_conda_types = { path = "../rattler_conda_types", version = "0.29.0", default-features = false }
rattler_digest = { path = "../rattler_digest", version = "1.0.3", default-features = false }
rattler_libsolv_c = { path = "../rattler_libsolv_c", version = "1.0.3", default-features = false, optional = true }
libc = { version = "0.2" , optional = true }
chrono = { version = "0.4.38", default-features = false, features = [
    "std",
    "serde",
    "alloc",
] }
thiserror = "1.0"
tracing = "0.1.40"
itertools = "0.13.0"
url = { version = "2.5.2" }
tempfile = "3.13.0"
resolvo = { version = "0.8.3" , optional = true }
futures = { version = "0.3.31", optional = true }
serde = { version = "1.0.214" , optional = true }

[features]
default = ["resolvo"]
libsolv_c = ["rattler_libsolv_c", "libc"]
resolvo = ["dep:resolvo", "dep:futures"]

[[bench]]
name = "bench"
harness = false

[[bench]]
name = "sorting_bench"
harness = false

[package.metadata.docs.rs]
all-features = true
