[tool.poetry]
name = "pyinvc"
version = "0.1.2"
description = ""
authors = ["Alireza <arg274@gmail.com>"]
readme = "README.md"
packages = [{include = "billing"}]

[tool.poetry.dependencies]
python = "^3.12"
httpx = "^0.27.2"
python-decouple = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
