[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "whatsapp_messager"
version = "0.0.2"
description = "WhatsApp message sender using WhatsApp Business API"
readme = "README.md"
authors = [{ name = "John Gbaya-Kokoya", email = "gbayakokoyajohnjr@gmail.com" }]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
keywords = ["whatsapp", "messaging", "automation", "api"]
dependencies = [
    "requests>=2.25.0",
    "setuptools>=42.0.0",
]
requires-python = ">=3.7"

[project.urls]
Homepage = "https://github.com/John-sys/whatsapp-sender_library?tab=readme-ov-file"
Documentation = "https://github.com/John-sys/whatsapp-sender_library?tab=readme-ov-file"
Repository = "https://github.com/John-sys/whatsapp-sender_library"
Issues = "https://github.com/John-sys/whatsapp-sender_library/issues"

[tool.setuptools]
packages = ["whatsapp_messager"]
