[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "django-pycorpkit"
version = "1.0.4"
description = "Reusable functionality"
readme = "README.rst"
authors = [
    {name = "Josephat Macharia", email = "josemash4@gmail.com"},
]
license = {text = "MIT"}

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"
python_files = ["test_*.py"]
addopts = "-v"
django_find_project = false
pythonpath = [
    ".",
    "tests"
]

[tool.flake8]
max-line-length = 99

requires-python = ">=3.8"
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 5.0",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
dependencies = [
    "Django>=5.0.6",
    "requests>=2.32.3",
    "psycopg2-binary>=2.9.9",
    "celery>=5.4.0",
    "djangorestframework>=3.15.1",
    "phonenumbers>=8.13.37",
    "django-phonenumber-field>=7.3.0",
    "django-filter>=24.2",
    "pytz>=2024.1",
    "django_rest_passwordreset>=1.4.1",
    "djangorestframework-simplejwt>=5.3.1",
    "python-magic>=0.4.27",  # interface to the libmagic file type identification library
    "PyJWT>=2.9.0",  # encode JSON webtokens
]
[project.urls]
Homepage = "https://django-pycorpkit.readthedocs.io/en/latest/index.html"

[project.optional-dependencies]
test = [
    "pytest>=8.2.1",
    "pytest-django>=4.8.0",
    "model-bakery>=1.18.1",
    "flake8",
    "isort",
    "black",
    "tox",
    "coverage",
    "pytest-cov",
]

[tool.hatch.build.targets.wheel]
packages = ["pycorpkit"]