[project]
name = "opentrons_sila2_server"
version = "0.2.9"
requires-python = ">=3.8"
dependencies = [
    "sila2>=0.12.0",
    "typer>=0.12.0",
    "opentrons>=8.1.0",
]

[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["opentrons_sila2_server*"]

[tool.setuptools.package-data]
"opentrons_sila2_server.generated" = [
    "*/*.sila.xml",
    "*/*.proto",
]
