[tool.poetry]
name = "kumo-cli"
version = "0.3.0"
description = "Ferramenta CLI para build e deploy em orquestradores de containers"
authors = ["Diego Lopes <djkakaroto@gmail.com>"]
repository = "https://github.com/LHForceTech/kumo"
maintainers = ["LH Force Tech", "Diego Lopes <djkakaroto@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "kumo", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.9.2"
typer = "^0.12.5"
fabric = "^3.2.2"
pyyaml = "^6.0.2"
jinja2 = "^3.1.4"
docker = "^7.1.0"

[tool.poetry.scripts]
kumo = "kumo.cmd.cli:app"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
isort = "^5.13.2"
pylint = "^3.3.1"
mkdocs = "^1.6.1"
mkdocs-material = "^9.5.43"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
