[tool.poetry]
name = "pldag-solver-sdk"
version = "0.1.4"
description = "Python SDK package for Solver API"
authors = ["znittzel <rikard@ourstudio.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"
pldag = "^0.10.0"

[tool.poetry.dev-dependencies]
# Add your development dependencies here
pytest = "^8.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
