[tool.poetry]
name = "gitlab-ci-script-linter"
version = "0.1.3"
description = "Collate expanded .gitlab-ci.yml script sections and lint scripts with Shellcheck"
authors = ["Sydney Chadwick <pseudossc@gmail.com>"]
readme = "README.md"
packages = [{include = "src"}]
license = "GPLv3"
homepage = "https://gitlab.com/SydneyChadwick/gitlab-ci-linter"
repository = "https://gitlab.com/SydneyChadwick/gitlab-ci-linter"

include = [
    "LICENSE",
]

[tool.poetry.scripts]
gl-ci-lint = "src.main:main"

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "def __str__",
    "if self.debug",
    "if settings.debug",
    "if settings.testing",
    "if __name__ == .__main__.:",
]

[tool.poetry.dependencies]
python = "^3.12"
argparse = "^1.4.0"
requests = "^2.32.3"
ruamel-yaml = "^0.18.6"

[tool.poetry.group.dev.dependencies]
coverage = "^7.4.4"
pytest-cov = "^5.0.0"
pylint = "^3.1.0"
black = "^24.3.0"
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
