[build-system]
requires = ["setuptools>=66.0"]
build-backend = "setuptools.build_meta"

[project]
name = "morilint"
version = "0.1.3"
description = "Мощный, либеральный, классный - Проверит сообщения, скажет, что не так"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Alexander Seryakov", email = "seryakov78116@gmail.com"}
]
dependencies = ['exceptiongroup>=1.1.3; python_version<"3.12"', 'rich<=13.9.3']

[project.scripts]
morilint = "mori_lint.main:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]