[tool.poetry]
name = "schemas_ses"
version = "0.3.9"
description = ""
authors = ["machkouroke <machkour20.mo1@gmail.com>"]
readme = "README.md"
packages = [{include = "Schemas_ses"}]

[tool.poetry.dependencies]
fastapi = "^0.115.0"
python = "^3.11"
pydantic = {extras = [ "email"], version = "^2.8.2"}
pymongo = "^4.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
